Dir {
  ArchiveDir ".";
  CacheDir "./.cache";
};

Default {
  Packages::Compress ". gzip";
};

TreeDefault {
  Directory "pool/$(SECTION)";
  BinCacheDB "packages-$(ARCH).db";
};

Tree "dists/trixie" {
  Sections "main tools science test";
  Architectures "amd64";
};
