APT::FTPArchive::Release::Origin "dev-jam";
APT::FTPArchive::Release::Label "dev-jam";
APT::FTPArchive::Release::Suite "trixie";
APT::FTPArchive::Release::Codename "trixie";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main tools science test";
